/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import business.Catalog;
import business.CatalogDirectory;
import java.awt.CardLayout;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Siddhant
 */
public class CustomerMngCatalogJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private CatalogDirectory catalogDirectory;

    /**
     * Creates new form CustomerMngCatalogJPanel
     */
     CustomerMngCatalogJPanel(JPanel userProcessContainer, CatalogDirectory catalogDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.catalogDirectory = catalogDirectory;
        tblCustomerCatalog.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 16));
        populateTable();
    }
     
     public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblCustomerCatalog.getModel();
        dtm.setRowCount(0);
        for (Catalog catalog : catalogDirectory.getCataloglist()) {
            Object[] row = new Object[4];
            row[0] = catalog;
            row[1] = catalog.getModelNumber();
            row[2] = catalog.getVendorName();
            row[3] = catalog.getProdBasePrice();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomerCatalog = new javax.swing.JTable();
        txtSearchbyProductName = new javax.swing.JTextField();
        txtSearchbyModelNumber = new javax.swing.JTextField();
        txtSearchbyVendorName = new javax.swing.JTextField();
        txtSearchbyBasePrice = new javax.swing.JTextField();
        btnViewDetail = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnSearchbyProductName = new javax.swing.JButton();
        btnSearchbyModelNumber = new javax.swing.JButton();
        btnSearchbyVendorName = new javax.swing.JButton();
        btnSearchbyBasePrice = new javax.swing.JButton();

        tblCustomerCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Model Number", "Vendor Name", "Base Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCustomerCatalog);

        btnViewDetail.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnViewDetail.setText("View Detail");
        btnViewDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSearchbyProductName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSearchbyProductName.setText("Search by Product Name:");
        btnSearchbyProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchbyProductNameActionPerformed(evt);
            }
        });

        btnSearchbyModelNumber.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSearchbyModelNumber.setText("Search by Model Number:");
        btnSearchbyModelNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchbyModelNumberActionPerformed(evt);
            }
        });

        btnSearchbyVendorName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSearchbyVendorName.setText("Search by Vendor Name:");
        btnSearchbyVendorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchbyVendorNameActionPerformed(evt);
            }
        });

        btnSearchbyBasePrice.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSearchbyBasePrice.setText("Search by Base Price:");
        btnSearchbyBasePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchbyBasePriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchbyProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchbyModelNumber)
                            .addComponent(btnSearchbyVendorName, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchbyBasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSearchbyBasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSearchbyVendorName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                .addComponent(txtSearchbyModelNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtSearchbyProductName, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(btnViewDetail))))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchbyProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchbyProductName))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchbyModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchbyModelNumber))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchbyVendorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchbyVendorName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchbyBasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchbyBasePrice))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewDetail)
                    .addComponent(btnBack))
                .addContainerGap(350, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchbyProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchbyProductNameActionPerformed
        // TODO add your handling code here:
        String ProductName = txtSearchbyProductName.getText();
        if ((ProductName.isEmpty()) || (ProductName.startsWith(" "))) {
            JOptionPane.showMessageDialog(this, "Please enter Product Name", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Catalog catalog = catalogDirectory.searchCatalog(txtSearchbyProductName.getText());
        if (catalog == null) {
            JOptionPane.showMessageDialog(this, "Product Name does not exist", "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
          //enter the code here to update the table automatically
        }
    }//GEN-LAST:event_btnSearchbyProductNameActionPerformed

    private void btnSearchbyModelNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchbyModelNumberActionPerformed
        // TODO add your handling code here:
        String ModelNumber = txtSearchbyModelNumber.getText();
        if ((ModelNumber.isEmpty()) || (ModelNumber.startsWith(" "))) {
            JOptionPane.showMessageDialog(this, "Please enter Model Number", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Catalog catalog = catalogDirectory.searchCatalog(txtSearchbyProductName.getText());
        if (catalog == null) {
            JOptionPane.showMessageDialog(this, "Model Number does not exist", "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
          //enter the code here to update the table automatically
        }
    }//GEN-LAST:event_btnSearchbyModelNumberActionPerformed

    private void btnSearchbyVendorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchbyVendorNameActionPerformed
        // TODO add your handling code here:
        String VendorName = txtSearchbyVendorName.getText();
        if ((VendorName.isEmpty()) || (VendorName.startsWith(" "))) {
            JOptionPane.showMessageDialog(this, "Please enter Vendor Name", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Catalog catalog = catalogDirectory.searchCatalog(txtSearchbyProductName.getText());
        if (catalog == null) {
            JOptionPane.showMessageDialog(this, "Vendor Name does not exist", "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
          //enter the code here to update the table automatically
        }
    }//GEN-LAST:event_btnSearchbyVendorNameActionPerformed

    private void btnSearchbyBasePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchbyBasePriceActionPerformed
        // TODO add your handling code here:
        String BasePrice = txtSearchbyBasePrice.getText();
        if ((BasePrice.isEmpty()) || (BasePrice.startsWith(" "))) {
            JOptionPane.showMessageDialog(this, "Please enter Base Price", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Catalog catalog = catalogDirectory.searchCatalog(txtSearchbyProductName.getText());
        if (catalog == null) {
            JOptionPane.showMessageDialog(this, "Base Price does not exist", "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
          //enter the code here to update the table automatically
        }
        
    }//GEN-LAST:event_btnSearchbyBasePriceActionPerformed

    private void btnViewDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCustomerCatalog.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select any row", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            Catalog catalog = (Catalog) tblCustomerCatalog.getValueAt(selectedRow, 0);
            CustomerViewCatalogJPanel panel = new CustomerViewCatalogJPanel(userProcessContainer, catalog);
            userProcessContainer.add("CustomerViewCatalogJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnViewDetailActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearchbyBasePrice;
    private javax.swing.JButton btnSearchbyModelNumber;
    private javax.swing.JButton btnSearchbyProductName;
    private javax.swing.JButton btnSearchbyVendorName;
    private javax.swing.JButton btnViewDetail;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCustomerCatalog;
    private javax.swing.JTextField txtSearchbyBasePrice;
    private javax.swing.JTextField txtSearchbyModelNumber;
    private javax.swing.JTextField txtSearchbyProductName;
    private javax.swing.JTextField txtSearchbyVendorName;
    // End of variables declaration//GEN-END:variables
}
