/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import business.Catalog;
import business.Vendor;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Siddhant
 */
public class ViewCatalogJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private Catalog catalog;
    private Vendor vendor;

    /**
     * Creates new form ViewCatalogJPanel
     */

    ViewCatalogJPanel(JPanel userProcessContainer, Catalog catalog) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.catalog = catalog;
        populateCatalogDetails();
       // btnSave.setEnabled(false);
       // btnUpdate.setEnabled(true);
        txtProductName.setEnabled(false);
        txtModelNumber.setEnabled(false);
        txtVendorName.setEnabled(false);
        txtDescription.setEnabled(false);
        txtBasePrice.setEnabled(false);
        txtCeilingPrice.setEnabled(false);
        txtFloorPrice.setEnabled(false);
        txtFeature.setEnabled(false);
        txtBenefits.setEnabled(false); 
    }
    
    private void populateCatalogDetails() {
        txtProductName.setText(catalog.getProductName());
        txtModelNumber.setText(catalog.getModelNumber());
        txtVendorName.setText(catalog.getVendorName());
        txtDescription.setText(catalog.getProductDescription());
        txtBasePrice.setText(String.valueOf(catalog.getProdBasePrice()));
        txtCeilingPrice.setText(String.valueOf(catalog.getProdCeilingPrice()));
        txtFloorPrice.setText(String.valueOf(catalog.getProdFloorPrice()));
        txtFeature.setText(catalog.getProdFeature());
        txtBenefits.setText(catalog.getBenefits());
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProductName = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        lblModelNumber = new javax.swing.JLabel();
        txtModelNumber = new javax.swing.JTextField();
        lblVendorName = new javax.swing.JLabel();
        txtVendorName = new javax.swing.JTextField();
        lblProductDescription = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        lblBasePrice = new javax.swing.JLabel();
        txtBasePrice = new javax.swing.JTextField();
        lblCeilingPrice = new javax.swing.JLabel();
        txtCeilingPrice = new javax.swing.JTextField();
        lblFloorPrice = new javax.swing.JLabel();
        txtFloorPrice = new javax.swing.JTextField();
        lblProdFeature = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFeature = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBenefits = new javax.swing.JTextArea();
        lblProdBenefits = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblProductName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblProductName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblProductName.setText("Product Name:");
        lblProductName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtProductName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtProductName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblModelNumber.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblModelNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblModelNumber.setText("Model Number:");
        lblModelNumber.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtModelNumber.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtModelNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblVendorName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblVendorName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblVendorName.setText("Vendor Name:");
        lblVendorName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtVendorName.setEditable(false);
        txtVendorName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtVendorName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblProductDescription.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblProductDescription.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblProductDescription.setText("Description:");
        lblProductDescription.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtDescription.setLineWrap(true);
        txtDescription.setRows(5);
        txtDescription.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane3.setViewportView(txtDescription);

        lblBasePrice.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblBasePrice.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBasePrice.setText("Base Price:");
        lblBasePrice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtBasePrice.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtBasePrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCeilingPrice.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblCeilingPrice.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCeilingPrice.setText("Ceiling Price:");
        lblCeilingPrice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtCeilingPrice.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtCeilingPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblFloorPrice.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblFloorPrice.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFloorPrice.setText("Floor Price:");

        txtFloorPrice.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtFloorPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblProdFeature.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblProdFeature.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblProdFeature.setText("Features:");
        lblProdFeature.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtFeature.setColumns(20);
        txtFeature.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtFeature.setLineWrap(true);
        txtFeature.setRows(5);
        txtFeature.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(txtFeature);

        txtBenefits.setColumns(20);
        txtBenefits.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtBenefits.setLineWrap(true);
        txtBenefits.setRows(5);
        txtBenefits.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(txtBenefits);

        lblProdBenefits.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblProdBenefits.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblProdBenefits.setText("Benefits:");
        lblProdBenefits.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHeader.setText("View Catalog");

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(398, 398, 398)
                .addComponent(lblHeader)
                .addContainerGap(372, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblVendorName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblProductDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBasePrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCeilingPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFloorPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                        .addComponent(lblModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblProdFeature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblProdBenefits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVendorName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBasePrice, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCeilingPrice, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFloorPrice, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(txtProductName))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblHeader)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVendorName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVendorName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProductDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCeilingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCeilingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFloorPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFloorPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProdFeature, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProdBenefits, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        //  ManageAccountJPanel manageAccountJPanel = (ManageAccountJPanel) component;
        VendorCatalogJPanel vendorCatalogJPanel = (VendorCatalogJPanel) component;
        vendorCatalogJPanel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtProductName.setEnabled(true);
        txtModelNumber.setEnabled(true);
        txtVendorName.setEnabled(false);
        txtDescription.setEnabled(true);
        txtBasePrice.setEnabled(true);
        txtCeilingPrice.setEnabled(true);
        txtFloorPrice.setEnabled(true);
        txtFeature.setEnabled(true);
        txtBenefits.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        String productName = txtProductName.getText();
        String modelNumber = txtModelNumber.getText();
        String vendorName = txtVendorName.getText();
        String description=txtDescription.getText();
        String feature=txtDescription.getText();
        String benefits=txtBenefits.getText();

        if ((productName.isEmpty()) || (productName.startsWith(" ")) || (modelNumber.isEmpty()) || (modelNumber.startsWith(" "))
            || (vendorName.isEmpty()) || (vendorName.startsWith(" "))) {
            JOptionPane.showMessageDialog(this, "Please fill all the details", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        float prodBasePrice;
        float prodCeilingPrice;
        float prodFloorPrice;

        String basePrice;
        String ceilingPrice;
        String floorPrice;

        basePrice=String.valueOf(txtBasePrice.getText());
        ceilingPrice=String.valueOf(txtCeilingPrice.getText());
        floorPrice=String.valueOf(txtFloorPrice.getText());

        if ((basePrice.isEmpty()) || (basePrice.startsWith(" ")) || (ceilingPrice.isEmpty()) || (ceilingPrice.startsWith(" "))
            || (floorPrice.isEmpty()) || (floorPrice.startsWith(" "))) {
            JOptionPane.showMessageDialog(this, "Please fill all the Price details", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            prodBasePrice=Float.parseFloat(txtBasePrice.getText());
            prodCeilingPrice=Float.parseFloat(txtCeilingPrice.getText());
            prodFloorPrice=Float.parseFloat(txtFloorPrice.getText());

            if ((prodBasePrice < 0) || (prodCeilingPrice < 0) || (prodFloorPrice < 0)) {
                JOptionPane.showMessageDialog(this, "No negative Values please", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please add appropriate values", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try{
            if (prodBasePrice>prodCeilingPrice){
                JOptionPane.showMessageDialog(this, "Base Price cannot be greater than Ceiling Price", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please add appropriate values", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try{
            if (prodBasePrice<prodFloorPrice){
                JOptionPane.showMessageDialog(this, "Floor Price cannot be greater than Base Price", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please add appropriate values", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Catalog catalog = catalogDirectory.addCatalog();
        catalog.setProductName(productName);
        catalog.setModelNumber(modelNumber);
        catalog.setVendorName(vendorName);
        catalog.setProductDescription(description);
        catalog.setProdBasePrice(prodBasePrice);
        catalog.setProdCeilingPrice(prodCeilingPrice);
        catalog.setProdFloorPrice(prodFloorPrice);
        catalog.setProdFeature(feature);
        catalog.setBenefits(benefits);

        JOptionPane.showMessageDialog(this, "Catalog Updated Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);

        txtProductName.setEnabled(false);
        txtModelNumber.setEnabled(false);
        txtVendorName.setEnabled(false);
        txtDescription.setEnabled(false);
        txtBasePrice.setEnabled(false);
        txtCeilingPrice.setEnabled(false);
        txtFloorPrice.setEnabled(false);
        txtFeature.setEnabled(false);
        txtBenefits.setEnabled(false);
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);

    }//GEN-LAST:event_btnSaveActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBasePrice;
    private javax.swing.JLabel lblCeilingPrice;
    private javax.swing.JLabel lblFloorPrice;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblProdBenefits;
    private javax.swing.JLabel lblProdFeature;
    private javax.swing.JLabel lblProductDescription;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblVendorName;
    private javax.swing.JTextField txtBasePrice;
    private javax.swing.JTextArea txtBenefits;
    private javax.swing.JTextField txtCeilingPrice;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextArea txtFeature;
    private javax.swing.JTextField txtFloorPrice;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtVendorName;
    // End of variables declaration//GEN-END:variables
}
