/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import business.Resume;
import business.ResumeHistory;
import java.awt.Image;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * @author Siddhant
 */
public class CreateResumeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    ButtonGroup gender = new ButtonGroup();
    ButtonGroup nationality = new ButtonGroup();
    ButtonGroup graduated = new ButtonGroup();
    private ResumeHistory rsh;
    //private Resume res;
    public String path;
    private String gen;
    private String nat;
    private String grad;
    // For Radio Buttons
    public String Java = "";
    public String Python = "";
    public String SQL = "";
    public String Cpp = "";
    public String Php = "";
    public String Matlab = "";

    public CreateResumeJPanel(ResumeHistory rsh) {                  //Parameterised Constructor
        initComponents();
        this.rsh = rsh;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lblHeading = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblContactNo = new javax.swing.JLabel();
        lblEmailId = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblStreetLine1 = new javax.swing.JLabel();
        lblStreetLine2 = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        contactNoTextField = new javax.swing.JTextField();
        emailIdTextField = new javax.swing.JTextField();
        streetLine1TextField = new javax.swing.JTextField();
        streetLine2TextField = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        lblZipCode = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        lblAffiliations = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        zipCodeTextField = new javax.swing.JTextField();
        affiliationsTextField = new javax.swing.JTextField();
        lblcareerObjective = new javax.swing.JLabel();
        lblEducationalQualifications = new javax.swing.JLabel();
        lblHighSchool = new javax.swing.JLabel();
        lblDate1 = new javax.swing.JLabel();
        lblGpa1 = new javax.swing.JLabel();
        degreeName1TextField = new javax.swing.JTextField();
        degreeDate1TextField = new javax.swing.JTextField();
        gpa1TextField = new javax.swing.JTextField();
        lblUnderGrdaduateSchool = new javax.swing.JLabel();
        lblDate2 = new javax.swing.JLabel();
        lblGpa2 = new javax.swing.JLabel();
        degreeName2TextField = new javax.swing.JTextField();
        degreeDate2TextField = new javax.swing.JTextField();
        gpa2TextField = new javax.swing.JTextField();
        lblWokExperience = new javax.swing.JLabel();
        lblLanguagesKnown = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        careerObjectiveTextField = new javax.swing.JTextArea();
        checkbox1 = new java.awt.Checkbox();
        submitBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        picBrowseBtn = new javax.swing.JButton();
        picPathTextField = new javax.swing.JTextField();
        countryTextField = new javax.swing.JComboBox<>();
        workExperienceTextField = new javax.swing.JComboBox<>();
        lblGender = new javax.swing.JLabel();
        btnMale = new javax.swing.JRadioButton();
        btnFemale = new javax.swing.JRadioButton();
        lblNationality = new javax.swing.JLabel();
        btnUSA = new javax.swing.JRadioButton();
        btnInternational = new javax.swing.JRadioButton();
        lblHaveYouGraduated = new javax.swing.JLabel();
        btnGraduatedYes = new javax.swing.JRadioButton();
        btnGraduatedNo = new javax.swing.JRadioButton();
        checkBoxJava = new javax.swing.JCheckBox();
        checkBoxPython = new javax.swing.JCheckBox();
        checkBoxCpp = new javax.swing.JCheckBox();
        checkBoxSQL = new javax.swing.JCheckBox();
        checkBoxMatlab = new javax.swing.JCheckBox();
        checkBoxPhp = new javax.swing.JCheckBox();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHeading.setText("Create a Resume");
        jPanel1.add(lblHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 24, -1, -1));

        lblFirstName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFirstName.setText("First Name:");
        lblFirstName.setPreferredSize(new java.awt.Dimension(143, 18));
        jPanel1.add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 91, 219, 26));

        lblLastName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblLastName.setText("Last Name:");
        lblLastName.setPreferredSize(new java.awt.Dimension(143, 18));
        jPanel1.add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 136, 219, 26));

        lblContactNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblContactNo.setText("Contact No:");
        lblContactNo.setPreferredSize(new java.awt.Dimension(143, 22));
        jPanel1.add(lblContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 275, 219, 26));

        lblEmailId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmailId.setText("Email id:");
        lblEmailId.setPreferredSize(new java.awt.Dimension(143, 22));
        jPanel1.add(lblEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 320, 219, 26));

        lblAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAddress.setText("Address");
        lblAddress.setPreferredSize(new java.awt.Dimension(143, 22));
        jPanel1.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 365, 219, 26));

        lblStreetLine1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblStreetLine1.setText("Street Line 1:");
        lblStreetLine1.setPreferredSize(new java.awt.Dimension(143, 22));
        jPanel1.add(lblStreetLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 414, 219, 26));

        lblStreetLine2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblStreetLine2.setText("Street Line 2:");
        lblStreetLine2.setPreferredSize(new java.awt.Dimension(143, 22));
        jPanel1.add(lblStreetLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 459, 219, 26));

        firstNameTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        firstNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(firstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 92, 312, 26));

        lastNameTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lastNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 137, 312, 26));

        contactNoTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        contactNoTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(contactNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 276, 312, 26));

        emailIdTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        emailIdTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(emailIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 321, 312, 26));

        streetLine1TextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        streetLine1TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(streetLine1TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 415, 312, 26));

        streetLine2TextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        streetLine2TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(streetLine2TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 460, 312, 26));

        lblCity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCity.setText("City:");
        lblCity.setPreferredSize(new java.awt.Dimension(143, 22));
        jPanel1.add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 504, 219, 26));

        lblZipCode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblZipCode.setText("Zip Code:");
        lblZipCode.setPreferredSize(new java.awt.Dimension(143, 22));
        jPanel1.add(lblZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 549, 219, 26));

        lblCountry.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCountry.setText("Country:");
        lblCountry.setPreferredSize(new java.awt.Dimension(143, 22));
        jPanel1.add(lblCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 594, 219, 26));

        lblAffiliations.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAffiliations.setText("Affiliations:");
        lblAffiliations.setPreferredSize(new java.awt.Dimension(143, 22));
        jPanel1.add(lblAffiliations, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 640, 219, 26));

        cityTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cityTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(cityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 505, 312, 26));

        zipCodeTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        zipCodeTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(zipCodeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 550, 312, 26));

        affiliationsTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        affiliationsTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(affiliationsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 641, 312, 26));

        lblcareerObjective.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblcareerObjective.setText("Career Objectives:");
        lblcareerObjective.setMaximumSize(new java.awt.Dimension(188, 22));
        lblcareerObjective.setPreferredSize(new java.awt.Dimension(219, 22));
        jPanel1.add(lblcareerObjective, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 685, -1, 26));

        lblEducationalQualifications.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEducationalQualifications.setText("Education Qualifications");
        jPanel1.add(lblEducationalQualifications, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 807, -1, -1));

        lblHighSchool.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHighSchool.setText("High School:");
        jPanel1.add(lblHighSchool, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 847, 219, 26));

        lblDate1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDate1.setText("Date");
        jPanel1.add(lblDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 847, -1, 26));

        lblGpa1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGpa1.setText("GPA");
        jPanel1.add(lblGpa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 847, -1, 26));

        degreeName1TextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        degreeName1TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(degreeName1TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 848, 312, 26));

        degreeDate1TextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        degreeDate1TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(degreeDate1TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 848, 150, 26));

        gpa1TextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        gpa1TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(gpa1TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(852, 848, 50, 26));

        lblUnderGrdaduateSchool.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUnderGrdaduateSchool.setText("Under Graduate School:");
        jPanel1.add(lblUnderGrdaduateSchool, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 892, 219, 29));

        lblDate2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDate2.setText("Date");
        jPanel1.add(lblDate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 892, -1, 29));

        lblGpa2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGpa2.setText("GPA");
        jPanel1.add(lblGpa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 892, -1, 29));

        degreeName2TextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        degreeName2TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(degreeName2TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 893, 312, 29));

        degreeDate2TextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        degreeDate2TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(degreeDate2TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 893, 150, 29));

        gpa2TextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        gpa2TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(gpa2TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(852, 893, 50, 29));

        lblWokExperience.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblWokExperience.setText("Work Experience:");
        jPanel1.add(lblWokExperience, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 987, 219, 27));

        lblLanguagesKnown.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblLanguagesKnown.setText("Languages Known:");
        jPanel1.add(lblLanguagesKnown, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 1034, 219, 29));

        careerObjectiveTextField.setColumns(20);
        careerObjectiveTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        careerObjectiveTextField.setLineWrap(true);
        careerObjectiveTextField.setRows(5);
        careerObjectiveTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(careerObjectiveTextField);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 685, 312, -1));

        checkbox1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        checkbox1.setLabel("All the above information is true and correct to the best of my knowledge.");
        checkbox1.setName(""); // NOI18N
        jPanel1.add(checkbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 1186, -1, -1));

        submitBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 1251, -1, -1));

        resetBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.setPreferredSize(new java.awt.Dimension(87, 31));
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        jPanel1.add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 1251, -1, -1));

        picBrowseBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        picBrowseBtn.setText("Browse Image");
        picBrowseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                picBrowseBtnActionPerformed(evt);
            }
        });
        jPanel1.add(picBrowseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 365, -1, -1));

        picPathTextField.setEditable(false);
        picPathTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        picPathTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(picPathTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 321, 312, 26));

        countryTextField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USA", "India", "China", "United Kingdom" }));
        countryTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(countryTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 596, 312, 26));

        workExperienceTextField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0-2 Years", "2-4 Years", "4-7 Years", "7 Years and Above" }));
        workExperienceTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(workExperienceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 989, 312, 27));

        lblGender.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGender.setText("Gender:");
        jPanel1.add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 181, 219, 29));

        btnMale.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnMale.setText("Male");
        btnMale.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnMaleStateChanged(evt);
            }
        });
        jPanel1.add(btnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 182, 150, -1));

        btnFemale.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnFemale.setText("Female");
        btnFemale.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnFemaleStateChanged(evt);
            }
        });
        jPanel1.add(btnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 182, 150, -1));

        lblNationality.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNationality.setText("Nationality:");
        jPanel1.add(lblNationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 228, 219, 29));

        btnUSA.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnUSA.setText("USA");
        btnUSA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnUSAStateChanged(evt);
            }
        });
        jPanel1.add(btnUSA, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 228, 150, -1));

        btnInternational.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnInternational.setText("International");
        btnInternational.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnInternationalStateChanged(evt);
            }
        });
        jPanel1.add(btnInternational, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 228, 150, -1));

        lblHaveYouGraduated.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHaveYouGraduated.setText("Have you Graduated:");
        jPanel1.add(lblHaveYouGraduated, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 940, 219, 29));

        btnGraduatedYes.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnGraduatedYes.setText("Yes");
        btnGraduatedYes.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnGraduatedYesStateChanged(evt);
            }
        });
        jPanel1.add(btnGraduatedYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 940, 150, -1));

        btnGraduatedNo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnGraduatedNo.setText("No");
        btnGraduatedNo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnGraduatedNoStateChanged(evt);
            }
        });
        jPanel1.add(btnGraduatedNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 940, 150, -1));

        checkBoxJava.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        checkBoxJava.setText("Java");
        checkBoxJava.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkBoxJavaStateChanged(evt);
            }
        });
        jPanel1.add(checkBoxJava, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 1035, 150, -1));

        checkBoxPython.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        checkBoxPython.setText("Python");
        checkBoxPython.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkBoxPythonStateChanged(evt);
            }
        });
        jPanel1.add(checkBoxPython, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 1035, 150, -1));

        checkBoxCpp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        checkBoxCpp.setText("Cpp");
        checkBoxCpp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkBoxCppStateChanged(evt);
            }
        });
        jPanel1.add(checkBoxCpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 1082, 150, -1));

        checkBoxSQL.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        checkBoxSQL.setText("SQL");
        checkBoxSQL.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkBoxSQLStateChanged(evt);
            }
        });
        jPanel1.add(checkBoxSQL, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 1082, 150, -1));

        checkBoxMatlab.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        checkBoxMatlab.setText("MATLAB");
        checkBoxMatlab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkBoxMatlabStateChanged(evt);
            }
        });
        jPanel1.add(checkBoxMatlab, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 1129, 150, -1));

        checkBoxPhp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        checkBoxPhp.setText("PHP");
        checkBoxPhp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkBoxPhpStateChanged(evt);
            }
        });
        jPanel1.add(checkBoxPhp, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 1129, 150, -1));

        jScrollPane3.setViewportView(jPanel1);

        add(jScrollPane3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void picBrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_picBrowseBtnActionPerformed
        // TODO add your handling code here:
        //Choosing image from JFile Chooser
        JFileChooser chooseimage = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("jpg files", "jpg");   // Restricting filter for jpg images
        chooseimage.setFileFilter(filter);
        int returnVal = chooseimage.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File f = chooseimage.getSelectedFile();
            String filename = f.getAbsolutePath();
            picPathTextField.setText(filename);
            ImageIcon icon = new ImageIcon(filename);
            path = filename;
        }
    }//GEN-LAST:event_picBrowseBtnActionPerformed

    // Method to reset all the fields
    public void resetFields() {
        firstNameTextField.setText("");
        lastNameTextField.setText("");
        contactNoTextField.setText("");
        emailIdTextField.setText("");
        streetLine1TextField.setText("");
        streetLine2TextField.setText("");
        cityTextField.setText("");
        zipCodeTextField.setText("");
        countryTextField.setSelectedItem("US");
        affiliationsTextField.setText("");
        careerObjectiveTextField.setText("");
        degreeName1TextField.setText("");
        degreeDate1TextField.setText("");
        gpa1TextField.setText("");
        degreeName2TextField.setText("");
        degreeDate2TextField.setText("");
        gpa2TextField.setText("");
        workExperienceTextField.setSelectedItem("0-2 Years");
        picPathTextField.setText("");
        gender.clearSelection();
        nationality.clearSelection();
        graduated.clearSelection();
        checkBoxJava.setSelected(false);
        checkBoxPython.setSelected(false);
        checkBoxSQL.setSelected(false);
        checkBoxCpp.setSelected(false);
        checkBoxPhp.setSelected(false);
        checkBoxMatlab.setSelected(false);
        checkbox1.setState(false);
    }
    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        //Making all the spaces blank in order to reset the fields
        resetFields();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // If Validate Field turns true then Call Set Text Method

        String firstName = firstNameTextField.getText();
        String lastName = lastNameTextField.getText();
        String contactNo = contactNoTextField.getText();
        String emailId = emailIdTextField.getText();
        String streetLine1 = streetLine1TextField.getText();
        String streetLine2 = streetLine2TextField.getText();
        String city = cityTextField.getText();
        String zipcode = zipCodeTextField.getText();
        String country = countryTextField.getSelectedItem().toString();
        String affiliations = affiliationsTextField.getText();
        String careerObjective = careerObjectiveTextField.getText();
        String degreeName1 = degreeName1TextField.getText();
        String degreeDate1 = degreeDate1TextField.getText();
        String degreeName2 = degreeName2TextField.getText();
        String degreeDate2 = degreeDate2TextField.getText();
        String workExperience = workExperienceTextField.getSelectedItem().toString();
        gender.add(btnMale);
        gender.add(btnFemale);
        nationality.add(btnUSA);
        nationality.add(btnInternational);
        graduated.add(btnGraduatedYes);
        graduated.add(btnGraduatedNo);

        // Float variable Validations
        double gpa1;
        double gpa2;
        try {
            gpa1 = Double.parseDouble(gpa1TextField.getText());
            gpa2 = Double.parseDouble(gpa2TextField.getText());
            if ((gpa1 <= 0) || (gpa1 > 4) || (gpa2 <= 0) || (gpa2 > 4)) {
                JOptionPane.showMessageDialog(this, "Please enter proper GPA", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please add appropriate values", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Email id Field Validation
        boolean isEmailCorrectlyFormatted = true;
        String email;
        try {
            isEmailCorrectlyFormatted = true;
            email = "^[_A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
            Pattern pattern = Pattern.compile(email);
            Matcher matcher = pattern.matcher(emailIdTextField.getText());
            if (!matcher.matches()) {
                isEmailCorrectlyFormatted = false;
                JOptionPane.showMessageDialog(this, "Please enter Email Id in proper format", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            } else {
                isEmailCorrectlyFormatted = true;
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please add appropriate values", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // To check if any field is empty or starts with blank space
        if ((firstName.isEmpty()) || (firstName.startsWith(" ")) || (lastName.isEmpty()) || (lastName.startsWith(" "))
                || (contactNo.isEmpty()) || (contactNo.startsWith(" ")) || (emailId.isEmpty()) || (emailId.startsWith(" "))
                || (streetLine1.isEmpty()) || (streetLine1.startsWith(" ")) || (streetLine2.isEmpty()) || (streetLine2.startsWith(" "))
                || (city.isEmpty()) || (city.startsWith(" ")) || (zipcode.isEmpty()) || (zipcode.startsWith(" ")) || (affiliations.isEmpty() || (affiliations.startsWith(" "))
                || (careerObjective.isEmpty())) || (careerObjective.startsWith(" ")) || (degreeName1.isEmpty()) || (degreeName1.startsWith(" "))
                || (degreeName2.isEmpty()) || (degreeName2.startsWith(" ")) || (degreeDate2.isEmpty()) || (degreeDate2.startsWith(" "))
                || (!(btnMale.isSelected() || (btnFemale.isSelected())))
                || (!(btnUSA.isSelected() || (btnInternational.isSelected())))
                || (!(btnGraduatedYes.isSelected() || (btnGraduatedNo.isSelected())))) {
            JOptionPane.showMessageDialog(this, "Please fill all the details", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Resume r = rsh.addResume();
        r.setFirstName(firstName);
        r.setLastName(lastName);
        r.setContactNo(contactNo);
        r.setEmailId(emailId);
        r.setStreetLn1(streetLine1);
        r.setStreetLn2(streetLine2);
        r.setCity(city);
        r.setZipCode(zipcode);
        r.setCountry(country);
        r.setAffiliations(affiliations);
        r.setCareerObjective(careerObjective);
        r.setDegreeName1(degreeName1);
        r.setDegreeDate1(degreeDate1);
        r.setGpa1(gpa1);
        r.setDegreeName2(degreeName2);
        r.setDegreeDate2(degreeDate2);
        r.setGpa2(gpa2);
        r.setWorkExperience(workExperience);
        r.setImage(path);
        r.setGender(gen);
        r.setNationality(nat);
        r.setGraduated(grad);
        r.setProgrammingLang(checkboxformat());
        // Display Success Message to user
        JOptionPane.showMessageDialog(this, "Resume Submitted Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
        resetFields();

        ImageIcon icon = new ImageIcon();

    }//GEN-LAST:event_submitBtnActionPerformed
    private String checkboxformat() {
        StringBuffer buffer = new StringBuffer();
        if (Java != "") {
            buffer = buffer.append(Java);
        }
        if (Python != "") {
            buffer.append(Python);
        }
        if (SQL != "") {
            buffer.append(SQL);
        }
        if (Cpp != "") {
            buffer.append(Cpp);
        }
        if (Php != "") {
            buffer.append(Php);
        }
        if (Matlab != "") {
            buffer.append(Matlab);
        }
        if (buffer.length() != 0) {
            buffer = buffer.deleteCharAt(0);

        }
        return buffer.toString();
    }


    private void btnMaleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnMaleStateChanged
        // TODO add your handling code here:
        if (btnMale.isSelected()) {
            //rsh.setButtonGender(true);
            gen = "Male";
            btnFemale.setSelected(false);
        } else {
            // rsh.setButtonGender(false);
        }
    }//GEN-LAST:event_btnMaleStateChanged

    private void btnFemaleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnFemaleStateChanged
        // TODO add your handling code here:
        if (btnFemale.isSelected()) {
            //rsh.setButtonGender(false);
            gen = "Female";
            btnMale.setSelected(false);
        } else {
            //rsh.setButtonGender(true);
        }
    }//GEN-LAST:event_btnFemaleStateChanged

    private void btnUSAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnUSAStateChanged
        // TODO add your handling code here:
        if (btnUSA.isSelected()) {
            nat = "International";
            btnInternational.setSelected(false);
        } else {
            //rsh.setButtonGender(true);
        }
    }//GEN-LAST:event_btnUSAStateChanged

    private void btnInternationalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnInternationalStateChanged
        // TODO add your handling code here:
        if (btnInternational.isSelected()) {
            nat = "USA";
            btnUSA.setSelected(false);
        } else {
            //rsh.setButtonGender(true);
        }
    }//GEN-LAST:event_btnInternationalStateChanged

    private void btnGraduatedYesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnGraduatedYesStateChanged
        // TODO add your handling code here:
        if (btnGraduatedYes.isSelected()) {
            grad = "Yes";
            btnGraduatedNo.setSelected(false);
        } else {
            // rsh.setButtonGender(false);
        }
    }//GEN-LAST:event_btnGraduatedYesStateChanged

    private void btnGraduatedNoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnGraduatedNoStateChanged
        // TODO add your handling code here:
        if (btnGraduatedNo.isSelected()) {
            grad = "No";
            btnGraduatedYes.setSelected(false);
        } else {
            //rsh.setButtonGender(true);
        }
    }//GEN-LAST:event_btnGraduatedNoStateChanged

    private void checkBoxJavaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkBoxJavaStateChanged
        // TODO add your handling code here:
        if (checkBoxJava.isSelected()) {
            Java = ", Java ";
        } else {
            Java = "";
        }
    }//GEN-LAST:event_checkBoxJavaStateChanged

    private void checkBoxPythonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkBoxPythonStateChanged
        // TODO add your handling code here:
        if (checkBoxPython.isSelected()) {
            Python = ", Python ";
        } else {
            Python = "";
        }
    }//GEN-LAST:event_checkBoxPythonStateChanged

    private void checkBoxSQLStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkBoxSQLStateChanged
        // TODO add your handling code here:
        if (checkBoxSQL.isSelected()) {
            SQL = ", SQL ";
        } else {
            SQL = "";
        }
    }//GEN-LAST:event_checkBoxSQLStateChanged

    private void checkBoxCppStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkBoxCppStateChanged
        // TODO add your handling code here:
        if (checkBoxCpp.isSelected()) {
            Cpp = ", Cpp ";
        } else {
            Cpp = "";
        }
    }//GEN-LAST:event_checkBoxCppStateChanged

    private void checkBoxPhpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkBoxPhpStateChanged
        // TODO add your handling code here:
        if (checkBoxPhp.isSelected()) {
            Php = ", Php ";
        } else {
            Php = "";
        }
    }//GEN-LAST:event_checkBoxPhpStateChanged

    private void checkBoxMatlabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkBoxMatlabStateChanged
        // TODO add your handling code here:
        if (checkBoxMatlab.isSelected()) {
            Matlab = ", Matlab ";
        } else {
            Matlab = "";
        }

    }//GEN-LAST:event_checkBoxMatlabStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField affiliationsTextField;
    private javax.swing.JRadioButton btnFemale;
    private javax.swing.JRadioButton btnGraduatedNo;
    private javax.swing.JRadioButton btnGraduatedYes;
    private javax.swing.JRadioButton btnInternational;
    private javax.swing.JRadioButton btnMale;
    private javax.swing.JRadioButton btnUSA;
    private javax.swing.JTextArea careerObjectiveTextField;
    private javax.swing.JCheckBox checkBoxCpp;
    private javax.swing.JCheckBox checkBoxJava;
    private javax.swing.JCheckBox checkBoxMatlab;
    private javax.swing.JCheckBox checkBoxPhp;
    private javax.swing.JCheckBox checkBoxPython;
    private javax.swing.JCheckBox checkBoxSQL;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JTextField contactNoTextField;
    private javax.swing.JComboBox<String> countryTextField;
    private javax.swing.JTextField degreeDate1TextField;
    private javax.swing.JTextField degreeDate2TextField;
    private javax.swing.JTextField degreeName1TextField;
    private javax.swing.JTextField degreeName2TextField;
    private javax.swing.JTextField emailIdTextField;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JTextField gpa1TextField;
    private javax.swing.JTextField gpa2TextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAffiliations;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblContactNo;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblDate1;
    private javax.swing.JLabel lblDate2;
    private javax.swing.JLabel lblEducationalQualifications;
    private javax.swing.JLabel lblEmailId;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGpa1;
    private javax.swing.JLabel lblGpa2;
    private javax.swing.JLabel lblHaveYouGraduated;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblHighSchool;
    private javax.swing.JLabel lblLanguagesKnown;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblNationality;
    private javax.swing.JLabel lblStreetLine1;
    private javax.swing.JLabel lblStreetLine2;
    private javax.swing.JLabel lblUnderGrdaduateSchool;
    private javax.swing.JLabel lblWokExperience;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JLabel lblcareerObjective;
    private javax.swing.JButton picBrowseBtn;
    private javax.swing.JTextField picPathTextField;
    private javax.swing.JButton resetBtn;
    private javax.swing.JTextField streetLine1TextField;
    private javax.swing.JTextField streetLine2TextField;
    private javax.swing.JButton submitBtn;
    private javax.swing.JComboBox<String> workExperienceTextField;
    private javax.swing.JTextField zipCodeTextField;
    // End of variables declaration//GEN-END:variables
}
