/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import business.Resume;                         //Importing Business Package
import business.ResumeHistory;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author Siddhant
 */
public class DisplayResumeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private ResumeHistory rsh;

    public DisplayResumeJPanel(ResumeHistory rsh) {     //Passing Parameters to constructors
        initComponents();
        this.rsh = rsh;
        tblResume.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 20));
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblResume.getModel();
        dtm.setRowCount(0);

        for (Resume rs : rsh.getResumeHistory()) {
            Object row[] = new Object[3];
            row[0] = rs;
            row[1] = rs.getLastName();
            row[2] = rs.getEmailId();
            dtm.addRow(row);
        }
    }

    // Creating a Separate Method and passing resume as Parameter
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        lblHeading = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblContactNo = new javax.swing.JLabel();
        lblEmailId = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblSteetLine1 = new javax.swing.JLabel();
        lblStreetLine2 = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        contactNoTextField = new javax.swing.JTextField();
        emailIdTextField = new javax.swing.JTextField();
        streetLine1TextField = new javax.swing.JTextField();
        streetLine2TextField = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        lblZipCode = new javax.swing.JLabel();
        lblAffiliations = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        zipCodeTextField = new javax.swing.JTextField();
        affiliationsTextField = new javax.swing.JTextField();
        lblCareerObjectives = new javax.swing.JLabel();
        lblEducationalQualifications = new javax.swing.JLabel();
        lblHighSchool = new javax.swing.JLabel();
        lblDate1 = new javax.swing.JLabel();
        lblGpa1 = new javax.swing.JLabel();
        degreeName1TextField = new javax.swing.JTextField();
        degreeDate1TextField = new javax.swing.JTextField();
        gpa1TextField = new javax.swing.JTextField();
        lblUnderGradSchool = new javax.swing.JLabel();
        lblDate2 = new javax.swing.JLabel();
        lblGpa2 = new javax.swing.JLabel();
        degreeName2TextField = new javax.swing.JTextField();
        degreeDate2TextField = new javax.swing.JTextField();
        gpa2TextField = new javax.swing.JTextField();
        lblWorkExp = new javax.swing.JLabel();
        lblLanguages = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        careerObjectiveTextField = new javax.swing.JTextArea();
        countryTextField = new javax.swing.JComboBox<>();
        workExperienceTextField = new javax.swing.JComboBox<>();
        lblGender = new javax.swing.JLabel();
        lblNationality = new javax.swing.JLabel();
        lblHaveYouGrad = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblResume = new javax.swing.JTable();
        btnViewDetails = new javax.swing.JButton();
        btnDeleteDetails = new javax.swing.JButton();
        picLabel = new javax.swing.JLabel();
        genderTextField = new javax.swing.JTextField();
        nationalityTextField = new javax.swing.JTextField();
        graduatedTextField = new javax.swing.JTextField();
        languagesTextField = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setEnabled(false);

        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHeading.setText("View Resume");

        lblFirstName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFirstName.setText("First Name:");
        lblFirstName.setPreferredSize(new java.awt.Dimension(143, 18));

        lblLastName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblLastName.setText("Last Name:");
        lblLastName.setPreferredSize(new java.awt.Dimension(143, 18));

        lblContactNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblContactNo.setText("Contact No:");
        lblContactNo.setPreferredSize(new java.awt.Dimension(143, 22));

        lblEmailId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmailId.setText("Email id:");
        lblEmailId.setPreferredSize(new java.awt.Dimension(143, 22));

        lblAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAddress.setText("Address");
        lblAddress.setPreferredSize(new java.awt.Dimension(143, 22));

        lblSteetLine1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSteetLine1.setText("Street Line 1:");
        lblSteetLine1.setPreferredSize(new java.awt.Dimension(143, 22));

        lblStreetLine2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblStreetLine2.setText("Street Line 2:");
        lblStreetLine2.setPreferredSize(new java.awt.Dimension(143, 22));

        firstNameTextField.setEditable(false);
        firstNameTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        firstNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lastNameTextField.setEditable(false);
        lastNameTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lastNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        contactNoTextField.setEditable(false);
        contactNoTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        contactNoTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        emailIdTextField.setEditable(false);
        emailIdTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        emailIdTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        streetLine1TextField.setEditable(false);
        streetLine1TextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        streetLine1TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        streetLine2TextField.setEditable(false);
        streetLine2TextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        streetLine2TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCity.setText("City:");
        lblCity.setPreferredSize(new java.awt.Dimension(143, 22));

        lblCountry.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCountry.setText("Country:");
        lblCountry.setPreferredSize(new java.awt.Dimension(143, 22));

        lblZipCode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblZipCode.setText("Zip Code:");
        lblZipCode.setPreferredSize(new java.awt.Dimension(143, 22));

        lblAffiliations.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAffiliations.setText("Affiliations:");
        lblAffiliations.setPreferredSize(new java.awt.Dimension(143, 22));

        cityTextField.setEditable(false);
        cityTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cityTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        zipCodeTextField.setEditable(false);
        zipCodeTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        zipCodeTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        affiliationsTextField.setEditable(false);
        affiliationsTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        affiliationsTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCareerObjectives.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCareerObjectives.setText("Career Objectives:");
        lblCareerObjectives.setMaximumSize(new java.awt.Dimension(188, 22));

        lblEducationalQualifications.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEducationalQualifications.setText("Education Qualifications");

        lblHighSchool.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHighSchool.setText("High School:");

        lblDate1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDate1.setText("Date");

        lblGpa1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGpa1.setText("GPA");

        degreeName1TextField.setEditable(false);
        degreeName1TextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        degreeName1TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        degreeDate1TextField.setEditable(false);
        degreeDate1TextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        degreeDate1TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gpa1TextField.setEditable(false);
        gpa1TextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        gpa1TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblUnderGradSchool.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUnderGradSchool.setText("Under Graduate School:");

        lblDate2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDate2.setText("Date");

        lblGpa2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGpa2.setText("GPA");

        degreeName2TextField.setEditable(false);
        degreeName2TextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        degreeName2TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        degreeDate2TextField.setEditable(false);
        degreeDate2TextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        degreeDate2TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gpa2TextField.setEditable(false);
        gpa2TextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        gpa2TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblWorkExp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblWorkExp.setText("Work Experience:");

        lblLanguages.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblLanguages.setText("Languages Known:");

        careerObjectiveTextField.setEditable(false);
        careerObjectiveTextField.setBackground(new java.awt.Color(240, 240, 240));
        careerObjectiveTextField.setColumns(20);
        careerObjectiveTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        careerObjectiveTextField.setLineWrap(true);
        careerObjectiveTextField.setRows(5);
        careerObjectiveTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(careerObjectiveTextField);

        countryTextField.setBackground(new java.awt.Color(240, 240, 240));
        countryTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        countryTextField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USA", "India", "China", "United Kingdom" }));
        countryTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        countryTextField.setEnabled(false);

        workExperienceTextField.setBackground(new java.awt.Color(240, 240, 240));
        workExperienceTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        workExperienceTextField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0-2 Years", "2-4 Years", "4-7 Years", "7 Years and Above" }));
        workExperienceTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        workExperienceTextField.setEnabled(false);

        lblGender.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGender.setText("Gender:");

        lblNationality.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNationality.setText("Nationality:");

        lblHaveYouGrad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHaveYouGrad.setText("Have you Graduated:");

        tblResume.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblResume.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Email Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblResume.setRowHeight(20);
        jScrollPane5.setViewportView(tblResume);
        if (tblResume.getColumnModel().getColumnCount() > 0) {
            tblResume.getColumnModel().getColumn(2).setResizable(false);
        }

        btnViewDetails.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        btnDeleteDetails.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnDeleteDetails.setText("Delete Details");
        btnDeleteDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDetailsActionPerformed(evt);
            }
        });

        picLabel.setPreferredSize(new java.awt.Dimension(120, 120));

        genderTextField.setEditable(false);
        genderTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        genderTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nationalityTextField.setEditable(false);
        nationalityTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nationalityTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        graduatedTextField.setEditable(false);
        graduatedTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        graduatedTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        languagesTextField.setEditable(false);
        languagesTextField.setBackground(new java.awt.Color(240, 240, 240));
        languagesTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        languagesTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEducationalQualifications))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblHighSchool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblUnderGradSchool, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(degreeName2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(degreeName1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDate1)
                                    .addComponent(lblDate2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(degreeDate1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(degreeDate2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblGpa2)
                                        .addGap(18, 18, 18)
                                        .addComponent(gpa2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblGpa1)
                                        .addGap(18, 18, 18)
                                        .addComponent(gpa1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                        .addComponent(lblCareerObjectives, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblAffiliations, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCountry, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblZipCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblEmailId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblStreetLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSteetLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNationality, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblContactNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnViewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(btnDeleteDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(emailIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(streetLine1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(streetLine2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(zipCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(countryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(affiliationsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lastNameTextField)
                                            .addComponent(firstNameTextField)
                                            .addComponent(genderTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                                            .addComponent(nationalityTextField))
                                        .addGap(152, 152, 152)
                                        .addComponent(picLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblLanguages, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(languagesTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblWorkExp, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHaveYouGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(graduatedTextField)
                                    .addComponent(workExperienceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(lblHeading)))
                .addContainerGap(591, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {genderTextField, nationalityTextField});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {affiliationsTextField, graduatedTextField, languagesTextField});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblHeading)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewDetails)
                    .addComponent(btnDeleteDetails))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93))
                            .addComponent(picLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(contactNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGender)
                            .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nationalityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNationality))
                        .addGap(18, 18, 18)
                        .addComponent(lblContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(streetLine1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSteetLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(streetLine2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStreetLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zipCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(affiliationsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAffiliations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCareerObjectives, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblEducationalQualifications)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblHighSchool)
                        .addGap(18, 18, 18)
                        .addComponent(lblUnderGradSchool))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(degreeName1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDate1)
                            .addComponent(degreeDate1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGpa1)
                            .addComponent(gpa1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(degreeName2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDate2)
                            .addComponent(degreeDate2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGpa2)
                            .addComponent(gpa2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(graduatedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHaveYouGrad))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWorkExp)
                    .addComponent(workExperienceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLanguages)
                    .addComponent(languagesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {affiliationsTextField, cityTextField, countryTextField, graduatedTextField, languagesTextField, lblAffiliations, lblCareerObjectives, lblCity, lblCountry, lblSteetLine1, lblStreetLine2, lblZipCode, streetLine1TextField, streetLine2TextField, zipCodeTextField});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {contactNoTextField, emailIdTextField, lblContactNo, lblEmailId});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {firstNameTextField, genderTextField, lastNameTextField, lblFirstName, lblGender, lblLastName, lblNationality, nationalityTextField});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {degreeName1TextField, lblHighSchool});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {degreeDate1TextField, degreeDate2TextField, degreeName2TextField, gpa1TextField, gpa2TextField, lblDate1, lblDate2, lblGpa1, lblGpa2, lblUnderGradSchool});

        jScrollPane4.setViewportView(jPanel2);

        add(jScrollPane4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblResume.getSelectedRow();

        if (selectedRow >= 0) {
            Resume rs = (Resume) tblResume.getValueAt(selectedRow, 0);
            firstNameTextField.setText(rs.getFirstName());
            lastNameTextField.setText(rs.getLastName());
            emailIdTextField.setText(rs.getEmailId());
            contactNoTextField.setText(rs.getContactNo());
            streetLine1TextField.setText(rs.getStreetLn1());
            streetLine2TextField.setText(rs.getStreetLn2());
            cityTextField.setText(rs.getCity());
            zipCodeTextField.setText(rs.getZipCode());
            // countryTextField.setText(String.valueOf(rs.getCountry()));
            affiliationsTextField.setText(rs.getAffiliations());
            careerObjectiveTextField.setText(rs.getCareerObjective());
            degreeName1TextField.setText(rs.getDegreeName1());
            degreeDate1TextField.setText(rs.getDegreeDate1());
            gpa1TextField.setText(String.valueOf(rs.getGpa1()));
            degreeName2TextField.setText(rs.getDegreeName2());
            degreeDate2TextField.setText(rs.getDegreeDate2());
            gpa2TextField.setText(String.valueOf(rs.getGpa2()));
            ImageIcon icon = new ImageIcon(rs.getImage());
            picLabel.setIcon(icon);
            genderTextField.setText(rs.getGender());
            nationalityTextField.setText(rs.getNationality());
            graduatedTextField.setText(rs.getGraduated());
            languagesTextField.setText(rs.getProgrammingLang());
        } else {
            JOptionPane.showMessageDialog(this, "Please select any row", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnDeleteDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblResume.getSelectedRow();

        if (selectedRow >= 0) {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "You want to delete selected Resume", "Confirm deletion", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
                Resume rs = (Resume) tblResume.getValueAt(selectedRow, 0);
                rsh.deleteResume(rs);
                JOptionPane.showMessageDialog(this, "Resume has been deleted", "Success", JOptionPane.INFORMATION_MESSAGE);
                populateTable();
                firstNameTextField.setText("");
                lastNameTextField.setText("");
                contactNoTextField.setText("");
                emailIdTextField.setText("");
                streetLine1TextField.setText("");
                streetLine2TextField.setText("");
                cityTextField.setText("");
                zipCodeTextField.setText("");
                countryTextField.setSelectedItem("US");
                affiliationsTextField.setText("");
                careerObjectiveTextField.setText("");
                degreeName1TextField.setText("");
                degreeDate1TextField.setText("");
                gpa1TextField.setText("");
                degreeName2TextField.setText("");
                degreeDate2TextField.setText("");
                gpa2TextField.setText("");
                workExperienceTextField.setSelectedItem("0-2 Years");
                languagesTextField.setText("");
                ImageIcon icon = new ImageIcon("");
                picLabel.setIcon(icon);
                genderTextField.setText("");
                nationalityTextField.setText("");
                graduatedTextField.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select any row", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteDetailsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField affiliationsTextField;
    private javax.swing.JButton btnDeleteDetails;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JTextArea careerObjectiveTextField;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JTextField contactNoTextField;
    private javax.swing.JComboBox<String> countryTextField;
    private javax.swing.JTextField degreeDate1TextField;
    private javax.swing.JTextField degreeDate2TextField;
    private javax.swing.JTextField degreeName1TextField;
    private javax.swing.JTextField degreeName2TextField;
    private javax.swing.JTextField emailIdTextField;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JTextField genderTextField;
    private javax.swing.JTextField gpa1TextField;
    private javax.swing.JTextField gpa2TextField;
    private javax.swing.JTextField graduatedTextField;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField languagesTextField;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAffiliations;
    private javax.swing.JLabel lblCareerObjectives;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblContactNo;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblDate1;
    private javax.swing.JLabel lblDate2;
    private javax.swing.JLabel lblEducationalQualifications;
    private javax.swing.JLabel lblEmailId;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGpa1;
    private javax.swing.JLabel lblGpa2;
    private javax.swing.JLabel lblHaveYouGrad;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblHighSchool;
    private javax.swing.JLabel lblLanguages;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblNationality;
    private javax.swing.JLabel lblSteetLine1;
    private javax.swing.JLabel lblStreetLine2;
    private javax.swing.JLabel lblUnderGradSchool;
    private javax.swing.JLabel lblWorkExp;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JTextField nationalityTextField;
    private javax.swing.JLabel picLabel;
    private javax.swing.JTextField streetLine1TextField;
    private javax.swing.JTextField streetLine2TextField;
    private javax.swing.JTable tblResume;
    private javax.swing.JComboBox<String> workExperienceTextField;
    private javax.swing.JTextField zipCodeTextField;
    // End of variables declaration//GEN-END:variables
}
